# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(413, 505)
        MainWindow.setMinimumSize(QtCore.QSize(396, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button_7.setGeometry(QtCore.QRect(10, 140, 71, 71))
        self.button_7.setObjectName("button_7")
        self.numbers = QtWidgets.QButtonGroup(MainWindow)
        self.numbers.setObjectName("numbers")
        self.numbers.addButton(self.button_7)
        self.button_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button_8.setGeometry(QtCore.QRect(90, 140, 71, 71))
        self.button_8.setObjectName("button_8")
        self.numbers.addButton(self.button_8)
        self.button_9 = QtWidgets.QPushButton(self.centralwidget)
        self.button_9.setGeometry(QtCore.QRect(170, 140, 71, 71))
        self.button_9.setObjectName("button_9")
        self.numbers.addButton(self.button_9)
        self.button_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button_5.setGeometry(QtCore.QRect(90, 220, 71, 71))
        self.button_5.setObjectName("button_5")
        self.numbers.addButton(self.button_5)
        self.button_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button_6.setGeometry(QtCore.QRect(170, 220, 71, 71))
        self.button_6.setObjectName("button_6")
        self.numbers.addButton(self.button_6)
        self.button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_1.setGeometry(QtCore.QRect(10, 300, 71, 71))
        self.button_1.setObjectName("button_1")
        self.numbers.addButton(self.button_1)
        self.button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_2.setGeometry(QtCore.QRect(90, 300, 71, 71))
        self.button_2.setObjectName("button_2")
        self.numbers.addButton(self.button_2)
        self.button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button_4.setGeometry(QtCore.QRect(10, 220, 71, 71))
        self.button_4.setObjectName("button_4")
        self.numbers.addButton(self.button_4)
        self.button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_3.setGeometry(QtCore.QRect(170, 300, 71, 71))
        self.button_3.setObjectName("button_3")
        self.numbers.addButton(self.button_3)
        self.button_0 = QtWidgets.QPushButton(self.centralwidget)
        self.button_0.setGeometry(QtCore.QRect(10, 380, 151, 71))
        self.button_0.setObjectName("button_0")
        self.numbers.addButton(self.button_0)
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear.setGeometry(QtCore.QRect(170, 380, 71, 71))
        self.button_clear.setObjectName("button_clear")
        self.numbers.addButton(self.button_clear)
        self.main_line = QtWidgets.QLineEdit(self.centralwidget)
        self.main_line.setGeometry(QtCore.QRect(10, 10, 391, 71))
        font = QtGui.QFont()
        font.setPointSize(38)
        self.main_line.setFont(font)
        self.main_line.setMaxLength(13)
        self.main_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.main_line.setReadOnly(True)
        self.main_line.setObjectName("main_line")
        self.button_plus = QtWidgets.QPushButton(self.centralwidget)
        self.button_plus.setGeometry(QtCore.QRect(250, 140, 71, 71))
        self.button_plus.setObjectName("button_plus")
        self.operators = QtWidgets.QButtonGroup(MainWindow)
        self.operators.setObjectName("operators")
        self.operators.addButton(self.button_plus)
        self.button_minus = QtWidgets.QPushButton(self.centralwidget)
        self.button_minus.setGeometry(QtCore.QRect(330, 140, 71, 71))
        self.button_minus.setObjectName("button_minus")
        self.operators.addButton(self.button_minus)
        self.button_multi = QtWidgets.QPushButton(self.centralwidget)
        self.button_multi.setGeometry(QtCore.QRect(250, 220, 71, 71))
        self.button_multi.setObjectName("button_multi")
        self.operators.addButton(self.button_multi)
        self.button_div = QtWidgets.QPushButton(self.centralwidget)
        self.button_div.setGeometry(QtCore.QRect(330, 220, 71, 71))
        self.button_div.setObjectName("button_div")
        self.operators.addButton(self.button_div)
        self.button_equals = QtWidgets.QPushButton(self.centralwidget)
        self.button_equals.setGeometry(QtCore.QRect(250, 380, 151, 71))
        self.button_equals.setObjectName("button_equals")
        self.button_sin = QtWidgets.QPushButton(self.centralwidget)
        self.button_sin.setGeometry(QtCore.QRect(250, 300, 71, 71))
        self.button_sin.setObjectName("button_sin")
        self.button_cos = QtWidgets.QPushButton(self.centralwidget)
        self.button_cos.setGeometry(QtCore.QRect(330, 300, 71, 71))
        self.button_cos.setObjectName("button_cos")
        self.button_A = QtWidgets.QPushButton(self.centralwidget)
        self.button_A.setGeometry(QtCore.QRect(10, 90, 91, 41))
        self.button_A.setObjectName("button_A")
        self.saved = QtWidgets.QButtonGroup(MainWindow)
        self.saved.setObjectName("saved")
        self.saved.addButton(self.button_A)
        self.button_B = QtWidgets.QPushButton(self.centralwidget)
        self.button_B.setGeometry(QtCore.QRect(110, 90, 91, 41))
        self.button_B.setObjectName("button_B")
        self.saved.addButton(self.button_B)
        self.button_C = QtWidgets.QPushButton(self.centralwidget)
        self.button_C.setGeometry(QtCore.QRect(210, 90, 91, 41))
        self.button_C.setObjectName("button_C")
        self.saved.addButton(self.button_C)
        self.button_D = QtWidgets.QPushButton(self.centralwidget)
        self.button_D.setGeometry(QtCore.QRect(310, 90, 91, 41))
        self.button_D.setObjectName("button_D")
        self.saved.addButton(self.button_D)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 413, 22))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        self.menuTrig = QtWidgets.QMenu(self.menubar)
        self.menuTrig.setObjectName("menuTrig")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuTrig.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.button_7.setText(_translate("MainWindow", "7"))
        self.button_8.setText(_translate("MainWindow", "8"))
        self.button_9.setText(_translate("MainWindow", "9"))
        self.button_5.setText(_translate("MainWindow", "5"))
        self.button_6.setText(_translate("MainWindow", "6"))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.button_4.setText(_translate("MainWindow", "4"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.button_0.setText(_translate("MainWindow", "0"))
        self.button_clear.setText(_translate("MainWindow", "C"))
        self.main_line.setText(_translate("MainWindow", "0"))
        self.button_plus.setText(_translate("MainWindow", "+"))
        self.button_minus.setText(_translate("MainWindow", "-"))
        self.button_multi.setText(_translate("MainWindow", "*"))
        self.button_div.setText(_translate("MainWindow", "/"))
        self.button_equals.setText(_translate("MainWindow", "="))
        self.button_sin.setText(_translate("MainWindow", "sin"))
        self.button_cos.setText(_translate("MainWindow", "cos"))
        self.button_A.setText(_translate("MainWindow", "A"))
        self.button_B.setText(_translate("MainWindow", "B"))
        self.button_C.setText(_translate("MainWindow", "C"))
        self.button_D.setText(_translate("MainWindow", "D"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.menuTrig.setTitle(_translate("MainWindow", "Trig"))
